name: Java API CI with Maven

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ensure target and cucumber directories exist
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/target/cucumber
          mkdir -p ${GITHUB_WORKSPACE}/target/cucumber-reports
          mkdir -p ${GITHUB_WORKSPACE}/cucumber/
          mkdir -p ${GITHUB_WORKSPACE}/cucumber-reports/json
          mkdir -p ${GITHUB_WORKSPACE}/cucumber-reports/html

      - name: Run tests
        run: mvn -Dtest=ApiFeatureTest test

      - name: Archive log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-log-api
          path: app.log

      - name: Generate Cucumber HTML report
        run: mvn -Dtest=ApiFeatureTest verify

      - name: Archive Cucumber JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report-api
          path: target/cucumber/cucumber.json

      - name: Archive Cucumber HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-reports-api
          path: target/cucumber-reports/