name: Java Chrome CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [22]
        browser: [chrome]
        network: [2G, 3G, 4G, WIFI, ETHERNET]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ensure required directories exist
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/target/cucumber
          mkdir -p ${GITHUB_WORKSPACE}/target/site
          mkdir -p ${GITHUB_WORKSPACE}/target/cucumber-reports
          mkdir -p ${GITHUB_WORKSPACE}/cucumber/
          mkdir -p ${GITHUB_WORKSPACE}/cucumber-reports/json
          mkdir -p ${GITHUB_WORKSPACE}/cucumber-reports/html

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run tests and generate reports
        run: |
          mvn clean test verify site -Dtest=CucumberFeatureTest -Dbrowser=${{ matrix.browser }} -Dconnection=${{ matrix.network }}

      - name: Archive log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-log-${{ matrix.browser }}-${{ matrix.network }}
          path: app.log

      - name: Archive Cucumber JSON report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report-${{ matrix.browser }}-${{ matrix.network }}
          path: target/cucumber/cucumber.json

      - name: Archive Cucumber HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-reports-${{ matrix.browser }}-${{ matrix.network }}
          path: target/cucumber-reports/

      - name: Archive Surefire HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-html-reports-${{ matrix.browser }}-${{ matrix.network }}
          path: target/site/