name: Java Unit Tests CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Ensure required directories exist
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/target/site

      - name: Run tests and generate reports
        run: mvn clean test site -Dtest=UnitTestsSuite

      - name: Archive log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-log-unit-tests
          path: app.log

      - name: Archive Surefire HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-html-report-unit-tests
          path: target/site/